// Generated by CoffeeScript 1.7.1

/*
                             Vortex Web

    This software and documentation are Copyright 2010 to 2014 PrismTech
    Limited and its licensees. All rights reserved. See file:

                           docs/LICENSE.html

    for full copyright notice and license terms.
 */

(function() {
  var connected, disconnect, drt, konsole, root, setupReaderSocket, socketMap, urlMap, z_;

  importScripts('vortex-web-client.js');

  root = this;

  z_ = coffez;

  drt = dds.runtime;

  connected = false;

  konsole = {};

  konsole.log = function(msg) {
    var cmd;
    cmd = drt.WriteLog(drt.EntityKind.Worker, msg);
    return root.postMessage(cmd);
  };

  socketMap = {};

  urlMap = {};

  setupReaderSocket = function(url, eid) {
    var socket;
    socket = new WebSocket(url);
    konsole.log("Created Websocket for DR at " + url);
    socketMap[eid] = socket;
    urlMap[eid] = url;
    socket.onopen = (function(_this) {
      return function(evt) {
        konsole.log("DR Websocket is open");
        return root.postMessage(drt.OnConnectedDataReader(url, eid));
      };
    })(this);
    socket.onclose = (function(_this) {
      return function(evt) {
        konsole.log("DR Websocket is closed");
        delete socketMap[eid];
        delete urlMap[eid];
        return root.postMessage(drt.OnDisconnectedDataReader(url, eid));
      };
    })(this);
    return socket.onmessage = (function(_this) {
      return function(evt) {
        evt = drt.OnDataAvailable(evt.data, eid);
        return root.postMessage(drt.OnDataAvailable(evt.data, eid));
      };
    })(this);
  };

  disconnect = function() {
    var eid, s;
    if (connected) {
      connected = false;
      for (eid in socketMap) {
        s = socketMap[eid];
        s.close();
        root.postMessage(OnDisconnectedDataReader(urlMap[eid], eid));
      }
      socketMap = {};
      return urlMap = {};
    }
  };

  root.onmessage = function(evt) {
    var cmd;
    cmd = evt.data;
    switch (false) {
      case !z_.match(cmd.h, drt.ConnectDataReaderCmd):
        konsole.log("Setting-up Socket for : " + cmd.eid + ", at " + cmd.url);
        return setupReaderSocket(cmd.url, cmd.eid);
      case !z_.match(cmd.h, drt.Connect):
        return connect();
      case !z_.match(cmd.h, drt.Disconnect):
        return disconnect();
      default:
        return konsole.log("Reader Worker Received Unknown Command!");
    }
  };

}).call(this);
